Add OpenAL dependency for openFrameworks compilation
Added libopenal-dev to audio library dependencies to fix the
compilation error:

  Package 'openal', required by 'virtual:world', not found
  makefileCommon/config.shared.mk:316: couldn't find openal
  pkg-config package or it's dependencies

OpenAL (Open Audio Library) is a required dependency for
openFrameworks audio support. The pkg-config file (openal.pc)
is provided by the libopenal-dev package on Debian/Ubuntu.

This was the last missing dependency preventing openFrameworks
from compiling on the 64-bit ARM build.